klopinet/basic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import sitemap

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^catalog/', include('catalog.urls', namespace="catalog")),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^uslugi/(?P<textpage_alias>[0-9a-z\-]+)/$', views.usluga, name='uslugi'),
    url(r'^(?P<textpage_alias>[0-9a-z\-]+)/$', views.textpage, name='textpage'),
    
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^b8c10b2f0684\.html$', views.yandex_mail, name='yandex_mail'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap' , {'sitemaps': sitemap.get_map()}),
    url(r'^yandex_(?P<yandex_verification_number>[0-9a-z]+)\.html$', views.yandex_verification, name='yandex_verification'),
    url(r'^google(?P<google_verification_number>[0-9a-z]+)\.html$', views.google_verification, name='google_verification'),
    url(r'^wmail_(?P<mail_verification_number>[0-9a-z]+)\.html$', views.mail_verification, name='mail_verification'),
]

klopinet/klopinet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('basic.urls', namespace="basic")),
]

klopinet/templates/main/__base.html
{% load i18n admin_static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<link rel="shortcut icon" href="/static/main/favicon.ico">
		 <title>{{ data.seo_title }}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="{{ data.seo_description}}">
		<meta name="keywords" content="{{ data.seo_keywords}}">
		<!-- css -->
		<link href="/static/main/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="/static/main/awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="/static/main/awesome/css/font-awesome.css">
		<link rel="stylesheet" href="/static/main/simple-line-icons/css/simple-line-icons.css">
		<link href="/static/main/css/fancybox/jquery.fancybox.css" rel="stylesheet"> 
		<link href="/static/main/css/flexslider.css" rel="stylesheet" />
		<link href="/static/main/js/owl-carousel/owl.carousel.css" rel="stylesheet">
		<link href="/static/main/css/style.css" rel="stylesheet" />
	</head>
	<body>
		<div id="wrapper" class="home-page">
			<!-- start header -->
				{% include "main/_header.html" %}
			<!-- end header -->
				{% block main_content %}{% endblock %}
			<!-- start Footer -->
				{% include "main/_footer.html" %}
			<!-- end Footer -->
		</div>
		<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
	<!-- javascript
		================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
			{% include "main/_scripts.html" %}
            <script>
                $(document).ready(function(){
                    if (window.location.pathname == '/ceny/'){
                        $('.aboutUs.textpage .row').css('column-count','1');
                    }
                    if (window.location.pathname == '/uslugi/'){
                        $('.aboutUs.textpage .row').css('column-count','1');
                    }
                })
            </script>
	</body>
</html>

klopinet/templates/main/_footer.html
		<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="widget">
						<h5 class="widgetheading">Наши контакты</h5>
						<address>
						<strong>Компания</strong><br>
						г. Москва, Дмитровское шоссе 98<br>
						 </address>
						<p>
							<i class="icon-phone"></i> +7 (919) 104-66-70<br>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div id="sub-footer">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="copyright">
							<p>
								<span>© 2016 Все права защищены</span></a>
							</p>
						</div>
					</div>
					<div class="col-lg-6">

					</div>
				</div>
			</div>
		</div>
		</footer>

klopinet/templates/main/_header.html
		<header>
			<div class="navbar navbar-default navbar-static-top">
				<div class="container">
					<div class="navbar-header">
						<div class="phonya"><b><i class="fa fa-clock-o" aria-hidden="true"></i>Круглосуточно, без выходных</b><span><i class="fa fa-phone" aria-hidden="true"></i>+7 (919) 104-66-70</span></div>
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/"><img src="/static/main/img/logo.png"><span>Klopinet</span></a>
					</div>
					<div class="navbar-collapse collapse ">
						<ul class="nav navbar-nav">
                            <li {% if host == "index" %}class="active"{% endif %}><a href="/">Главная</a></li>
                            {% for menu_item in menu %}
                                <li {% if menu_item.alias == host %}class="active"{% endif %}>
                                    <a href="{% url 'basic:textpage' menu_item.alias %}">
                                    {% if menu_item.menutitle %}
                                        {{ menu_item.menutitle }}{% else %}{{ menu_item.name }}
                                    {% endif %}
                                    </a>
                                    {% if menu_item.alias == "uslugi" %}
                                        <ul>
                                            {% for usluga in uslugi %}
                                            <li>
                                                <a href="{% url 'basic:uslugi' usluga.alias %}">
                                                    {% if usluga.menutitle %}
                                                        {{ usluga.menutitle }}{% else %}{{ usluga.name }}
                                                    {% endif %}
                                                </a>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </li>
                            {% endfor %}
						</ul>
                        <span class="slogan">Уничтожение насекомых быстро и на долго!</span>
					</div>
				</div>
			</div>
		</header>

klopinet/templates/main/_scripts.html
		<script src="/static/main/js/jquery.js"></script>
		<script src="/static/main/js/jquery.easing.1.3.js"></script>
		<script src="/static/main/js/bootstrap.min.js"></script>
		<script src="/static/main/js/jquery.fancybox.pack.js"></script>
		<script src="/static/main/js/jquery.fancybox-media.js"></script> 
		<script src="/static/main/js/portfolio/jquery.quicksand.js"></script>
		<script src="/static/main/js/portfolio/setting.js"></script>
		<script src="/static/main/js/jquery.flexslider.js"></script>
		<script src="/static/main/js/animate.js"></script>
		<script src="/static/main/js/owl-carousel/owl.carousel.js"></script>
		<script src="/static/main/js/custom.js"></script>
		{% autoescape off %}
		{% for script in scripts %}
                {{ script.content }}
        {% endfor %}
		{% endautoescape %}

klopinet/templates/main/contacts.html
{% extends "main/__base.html" %}
    {% block main_content %}
	<section id="inner-headline">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="pageTitle">Контакты</h1>
				</div>
			</div>
		</div>
	</section>
	<section id="content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ijBME7BdvsoGWs2itCN_iSsT-gpAa_74&width=100%&height=300&lang=ru_RU&sourceType=constructor&scroll=true"></script>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<br>
					<div class="alert alert-success {% if not success %}hidden{% endif %}" id="contactSuccess">
						<strong>Ваше сообщение успешно отправлено!</strong> 
					</div>
					<div class="alert alert-error {% if not error %}hidden{% endif %}" id="contactError">
						<strong>В сообщении содержатся ошибки!</strong> 
					</div>
					<div class="contact-form">
						<!--NOTE: Update your email Id in "contact_me.php" file in order to receive emails from your contact form-->
						<form id="contactForm" method="post"> 
                            {% csrf_token %}
							<div class="control-group">
								<div class="controls">
									{{ form.name }} 
									<p class="help-block">{{ form.name.errors }}</p>
								</div>
							</div> 	
							<div class="control-group">
								<div class="controls">
									{{ form.email }} 
                                    <p class="help-block">{{ form.name.email }}</p>
								</div>
							</div> 	
							<div class="control-group">
								<div class="controls">
									{{ form.message }} 
                                    <p class="help-block">{{ form.name.message }}</p>
								</div>
							</div> 		 
							<div id="success"> </div> <!-- For success/fail messages -->
							<button type="submit" class="btn btn-primary pull-right">Отправить</button><br />
						</form>
					</div>
				</div>
				<div class="col-md-6">
					<div class="span4">
						<div class="title-box clearfix "><h3 class="title-box_primary">Наши контакты</h3></div> 
						
						
						</p>
						<address>
						г. Москва,<br>
						Дмитровское шоссе 98.</strong><br>
						+7 (919) 104-66-70<br>
						</address> 
					</div> 
				</div>
			</div>
		</div>
	</section>
    {% endblock %}

klopinet/templates/main/index.html
{% extends "main/__base.html" %}
    {% block main_content %}
<section id="banner">
		<!-- Slider -->
		<div id="main-slider" class="flexslider">
			<ul class="slides">
			  <li>
				<img src="/static/main/img/s01.jpg" alt="" />
					 <div class="container">
						<div class="row">
							<div class="col-lg-12">
								<div class="flex-caption">
									<span>Дезинсекция</span> 
									<p>Уничтожение насекомых: клещей, ос, тараканов, блох, муравьев, моли и других ползающих и летающих.</p>  
								</div>
							</div>
						</div>
					</div>
			  </li>
			  <li>
				<img src="/static/main/img/22.jpg" alt="" />
					<div class="container">
						<div class="row" style="padding-bottom: 0;">
							<div class="col-lg-12">
								<div class="flex-caption">
									<span>Дезинсекция</span> 
									<p>Уничтожение насекомых: клещей, ос, тараканов, блох, муравьев, моли и других ползающих и летающих.</p>    
								</div>
							</div>
						</div>
					</div>
			  </li>
			</ul>
		</div>
		<!-- end slider -->
		</section>
		<section class="jumbobox">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div>
						<h1>{% if data.seo_h1 %}{{ data.seo_h1 }}{% else %}{{ data.name }}{% endif %}</h1>
						<img style="float: left; margin: 0 15px 15px 0; height: 200px;" src="/static/main/img/klopinet/des1.jpg"><p>Наша компания предоставляет услуги по дезинсекции помещений. Мы поможем избавиться вам от: мух, клопов, ос, короеда, тараканов, блох, муравьев.</p>
<p>Чтобы успешно уничтожить насекомых на работе или у себя дома, доверьте этот вопрос профессионалам, которые уже не первый год сталкиваются с дезинсекцией. У нашей компании большой опыт борьбы с "неприятными соседями". Качественная профессиональная работа наших специалистов, индивидуальный подход к каждой ситуации и комплексное решение задач.</p>
<p>Если в ваши планы не входит дезинсекция своими руками, то вы можете заказать уничтожение насекомых на нашем сайте. С помощью использования новейших средств дезинсекция (уничтожение насекомых, клопов, мух, ос, блох, муравьев, короеда) пройдет максимально качественно и без ущерба для человека, к тому же вы экономите свое время, а это самый ценный ресурс.</p>
						<div class="row our_services">
							<div class="col-md-12 col-sm-12 titled"><h2>Уничтожение насекомых</h2></div>
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="uslugi/unichtozhenie-bloh-borba-s-blohami/">Уничтожение блох</a>
								<img src="/static/main/img/bug/bloha.jpg">
							</div>
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="uslugi/unichtozhenie-muravev-borba-s-muravyami/">Уничтожение муравьев</a>
								<img src="/static/main/img/bug/mura.png">
							</div>
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="uslugi/unichtozhenie-os/">Уничтожение ос</a>
								<img src="/static/main/img/bug/wasp.jpg">
							</div>
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="uslugi/unichtozhenie-klopov/">Уничтожение клопов</a>
								<img src="/static/main/img/bug/klopp.jpg">
							</div>						
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="uslugi/unichtozhenie-tarakanov/">Уничтожение тараканов</a>
								<img src="/static/main/img/bug/tarak.jpg">
							</div>						
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="#">Уничтожение мух</a>
								<img src="/static/main/img/bug/sinek.jpg">
							</div>						
							<div class="col-md-3 col-sm-6 col-xs-12 usluga">
								<a href="#">Уничтожение короеда</a>
								<img src="/static/main/img/bug/koro.jpg">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		</section>
		<section id="content" style="padding-top: 0;">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<h2>Наши преимущества</h2>
					</div>
					<div class="skill-home">
						<div class="skill-home-solid clearfix"> 
							<div class="col-sm-6 col-md-3 text-center"> 
								<div class="box"> 
								<span class="icons c3">
									<i class="fa fa-check-circle icons"></i>
								</span>
									<div class="box-area">
										<h3>Качество</h3>
										<p>Мы предоставляем свои услуги дезинсекции уже более 10 лет</p>
									</div>
								</div>
							</div>
							<div class="col-sm-6 col-md-3 text-center">
								<div class="box"> 
									<span class="icons c1">
										<i class="fa fa-leaf icons"></i>
									</span>
									<div class="box-area">
										<h3>Безопасность</h3>
										<p>Методы борьбы с насекомыми безопасны для животных</p>
									</div>
								</div>
							</div>
							<div class="col-sm-6 col-md-3 text-center"> 
								<div class="box"> 
								<span class="icons c2">
									<i class="fa fa-tachometer icons"></i>
								</span>
									<div class="box-area">
										<h3>Скорость</h3>
										<p>Продолжительность обработки от насекомых составляет 45-60 мин.</p>
									</div>
								</div>
							</div>
							<div class="col-sm-6 col-md-3 text-center"> 
								<div class="box">
									<span class="icons c4">
										<i class="fa fa-money icons"></i>
									</span> 
									<div class="box-area">
										<h3>Доступные цены</h3> 
										<p>Профессиональные услуги дезинсекции по доступным ценам.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> 
		</section>
		<section class="aboutUs">
			<div class="container">
				<div class="row">
                    <article>
					{{ data.content|safe }}
                    </article>
				</div> 
			</div>
		</section>
    {% endblock %}

klopinet/templates/main/index3.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Prime Bootstrap Interior Design Web Template</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="description" content="" />
		<meta name="author" content="http://webthemez.com" />
		<!-- css -->
		<link href="css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="awesome/css/font-awesome.min.css">
		<link rel="stylesheet" href="awesome/css/font-awesome.css">
		<link rel="stylesheet" href="simple-line-icons/css/simple-line-icons.css">
		<link href="css/fancybox/jquery.fancybox.css" rel="stylesheet"> 
		<link href="css/flexslider.css" rel="stylesheet" />
		<link href="js/owl-carousel/owl.carousel.css" rel="stylesheet">
		<link href="css/style.css" rel="stylesheet" />
	</head>
	<body>
	<div id="wrapper" class="home-page">
		<!-- start header -->
		<header style="position: relative; height: 133px;">
			<div class="navbar navbar-default navbar-static-top">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="index.html"><i class="fa fa-envira" aria-hidden="true"></i> Название</a>
					</div>
					<div class="navbar-collapse collapse ">
						<ul class="nav navbar-nav">
							<li class="active"><a href="index.html">Главная</a></li> 
							<li><a href="index2.html">Услуги</a></li>
							<li><a href="index3.html">Цены</a></li>
							<li><a href="contact.html">Контакты</a></li>
						</ul>
					</div>
				</div>
			</div>
		</header>
		<!-- end header -->
		<section id="inner-headline">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h2 class="pageTitle">Цены</h2>
				</div>
			</div>
		</div>
		</section>
		<section class="aboutUs">
		<div class="container">
			<div class="row">
				<h2>Заголовок</h2>
				
				<table class="table table-bordered">
					<tr><th>Услуга</th><th>Цена</th></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
					<tr><td>Дезинсекция</td><td>700 руб.</td></tr>
				</table>
			</div> 
		</div>
		</section> 
		<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="widget">
						<h5 class="widgetheading">Наши контакты</h5>
						<address>
						<strong>Компания</strong><br>
						г. Москва<br>
						 </address>
						<p>
							<i class="icon-phone"></i> (123) 456-789 - 1255-12584 <br>
							<i class="icon-envelope-alt"></i> email@domainname.com
						</p>
					</div>
				</div>
			</div>
		</div>
		<div id="sub-footer">
			<div class="container">
				<div class="row">
					<div class="col-lg-6">
						<div class="copyright">
							<p>
								<span>© 2016 Все права защищены</span></a>
							</p>
						</div>
					</div>
					<div class="col-lg-6">

					</div>
				</div>
			</div>
		</div>
		</footer>
	</div>
	<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
	<!-- javascript
		================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
		<script src="js/jquery.js"></script>
		<script src="js/jquery.easing.1.3.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.fancybox.pack.js"></script>
		<script src="js/jquery.fancybox-media.js"></script> 
		<script src="js/portfolio/jquery.quicksand.js"></script>
		<script src="js/portfolio/setting.js"></script>
		<script src="js/jquery.flexslider.js"></script>
		<script src="js/animate.js"></script>
		<script src="js/owl-carousel/owl.carousel.js"></script>
		<script src="js/custom.js"></script>
	</body>
</html>

klopinet/templates/main/textpage.html
{% extends "main/__base.html" %}
    {% block main_content %}
		<section id="inner-headline">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h1 class="pageTitle">{% if data.seo_h1 %}{{ data.seo_h1 }}{% else %}{{ data.name }}{% endif %}</h1>
				</div>
			</div>
		</div>
		</section>
		<section class="aboutUs textpage">
		<div class="container">
			<div class="row">
                <article>
				{{ data.content|safe }}
                </article>
			</div> 
		</div>
		</section> 
    {% endblock %}